[package]
name = "Switchboard_Demo"
version = "0.0.0"

[addresses]
std = "0x1"
aptos_framework = "0x1"
switchboard = "0x14611263909398572be034debb2e61b6751cafbeaddd994b9a1250cb76b99d38"# Will change as we iterate on devnet
demo = "_"

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "f8bf8fdeec33c8c6ff3d1cbaf4990b9e54c2176a" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "f8bf8fdeec33c8c6ff3d1cbaf4990b9e54c2176a" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "f8bf8fdeec33c8c6ff3d1cbaf4990b9e54c2176a" }

[dependencies.Switchboard]
git = "https://github.com/switchboard-xyz/aptos-sdk.git"
subdir = "switchboard-move/switchboard/"
rev = "main"

